// <auto-generated />

using System.ComponentModel;
namespace mycompany.bu.process.plugin.Plugins.ProxyClasses
{
    public enum eApprovalStatus
    {
        /// <summary>
        /// <para>Approved</para>
        /// <para>Value = 100000000</para>
        /// </summary>
        [Description("Approved")]
        Approved = 100000000,

        /// <summary>
        /// <para>Rejected</para>
        /// <para>Value = 100000001</para>
        /// </summary>
        [Description("Rejected")]
        Rejected = 100000001,
    }
}
