// <auto-generated />

using System.ComponentModel;
namespace mycompany.bu.process.plugin.Plugins.ProxyClasses
{
    public enum eLeaveType
    {
        /// <summary>
        /// <para>Annual</para>
        /// <para>Value = 100000000</para>
        /// </summary>
        [Description("Annual")]
        Annual = 100000000,

        /// <summary>
        /// <para>Personal</para>
        /// <para>Value = 100000001</para>
        /// </summary>
        [Description("Personal")]
        Personal = 100000001,

        /// <summary>
        /// <para>Compassionate</para>
        /// <para>Value = 100000002</para>
        /// </summary>
        [Description("Compassionate")]
        Compassionate = 100000002,

        /// <summary>
        /// <para>Parental</para>
        /// <para>Value = 100000003</para>
        /// </summary>
        [Description("Parental")]
        Parental = 100000003,
    }
}
