// <auto-generated />

using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace mycompany.bu.process.plugin.Plugins.ProxyClasses
{
    [EntityLogicalNameAttribute("new_leaverequests")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    [DataContract(Name = "Entity", Namespace = "http://schemas.microsoft.com/xrm/2011/Contracts")]
    public partial class LeaveRequests : BaseProxyClass
    {
        public new const string LogicalName = "new_leaverequests";
        public const int ObjectTypeCode = 10101;
        public const string PrimaryIdAttribute = "new_leaverequestsid";
        public const string PrimaryNameAttribute = "new_name";
        
        static LeaveRequests()
        {
            BaseProxyClass.RegisterProxyType(typeof(LeaveRequests), "new_leaverequests");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public LeaveRequests() : base(new Entity("new_leaverequests")) { }
        public LeaveRequests(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<LeaveRequests>(); }

        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }

        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }

        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }

        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }

        private static Dictionary<string, eNumberOptions> _numberOptions;

        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }

        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }

        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }
        /// <summary>
        /// <para>Logical Name: stageid</para>
        /// </summary>
        [AttributeLogicalName("stageid")]
        public Guid _Deprecated_StageId
        {
            get
            {
                return this.GetPropertyValue<Guid>("stageid");
            }
            set
            {
                this.SetPropertyValue<Guid>("stageid", value, "_Deprecated_StageId");
            }
        }

        /// <summary>
        /// <para>Logical Name: traversedpath</para>
        /// <para>Max Length: 1250 characters</para>
        /// </summary>
        [AttributeLogicalName("traversedpath")]
        public string _Deprecated_TraversedPath
        {
            get
            {
                return this.GetPropertyValue<string>("traversedpath");
            }
            set
            {
                this.SetPropertyValue("traversedpath", value, 1250, "_Deprecated_TraversedPath");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_comments</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("new_comments")]
        public string Comments
        {
            get
            {
                return this.GetPropertyValue<string>("new_comments");
            }
            set
            {
                this.SetPropertyValue("new_comments", value, 100, "Comments");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdby</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        public EntityReference CreatedBy
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("createdby");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfby</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        public EntityReference CreatedBy_Delegate
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("createdonbehalfby");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdon</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        public DateTime? CreatedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("createdon");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdbyname")]
        public string CreatedByName
        {
            get
            {
                return this.GetPropertyValue<string>("createdbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdbyyominame")]
        public string CreatedByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("createdbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfbyname")]
        public string CreatedOnBehalfByName
        {
            get
            {
                return this.GetPropertyValue<string>("createdonbehalfbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: createdonbehalfbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfbyyominame")]
        public string CreatedOnBehalfByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("createdonbehalfbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_enddate</para>
        /// </summary>
        [AttributeLogicalName("new_enddate")]
        public DateTime? EndDate
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("new_enddate");
            }
            set
            {
                this.SetPropertyValue<DateTime?>("new_enddate", value, "EndDate");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_halfday</para>
        /// <para>True = Yes</para>
        /// <para>False = No</para>
        /// </summary>
        [AttributeLogicalName("new_halfday")]
        public bool? HalfDay
        {
            get
            {
                return this.GetPropertyValue<bool?>("new_halfday");
            }
            set
            {
                this.SetPropertyValue<bool?>("new_halfday", value, "HalfDay");
            }
        }

        /// <summary>
        /// Logical Name: new_hrapproval
        /// </summary>
        [AttributeLogicalName("new_hrapproval")]
        public eApprovalStatus? HRApproval
        {
            get
            {
                if (HRApproval_OptionSetValue != null) { return (eApprovalStatus)HRApproval_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.HRApproval_OptionSetValue = new OptionSetValue((int)value); }
                else this.HRApproval_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_hrapproval</para>
        /// </summary>
        [AttributeLogicalName("new_hrapproval")]
        public OptionSetValue HRApproval_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("new_hrapproval");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("new_hrapproval", value, "HRApproval_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string HRApproval_Text(IOrganizationService service)
        {
            return this.HRApproval_OptionSetValue.GetOptionSetText(service, this, "new_hrapproval");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string HRApproval_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.HRApproval_OptionSetValue.Value);
        }

        /// <summary>
        /// <para>Logical Name: importsequencenumber</para>
        /// <para>Minimum Value: -2147483648</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("importsequencenumber")]
        public int? ImportSequenceNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("importsequencenumber");
            }
            set
            {
                this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, "ImportSequenceNumber");
            }
        }

        /// <summary>
        /// <para>Key Property (Uniqueidentifier)</para>
        /// <para>Logical Name: new_leaverequestsid</para>
        /// </summary>
        [AttributeLogicalName("new_leaverequestsid")]
        public Guid LeaveRequestsId
        {
            get
            {
                return base.Id;
            }
            set
            {
                base.Id = value;
                base.SetPropertyValue("new_leaverequestsid", value, "LeaveRequestsId");
            }
        }

        /// <summary>
        /// Logical Name: new_overallstatus
        /// </summary>
        [AttributeLogicalName("new_overallstatus")]
        public eLeaveRequests_LeaveStatus? LeaveStatus
        {
            get
            {
                if (LeaveStatus_OptionSetValue != null) { return (eLeaveRequests_LeaveStatus)LeaveStatus_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.LeaveStatus_OptionSetValue = new OptionSetValue((int)value); }
                else this.LeaveStatus_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_overallstatus</para>
        /// </summary>
        [AttributeLogicalName("new_overallstatus")]
        public OptionSetValue LeaveStatus_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("new_overallstatus");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("new_overallstatus", value, "LeaveStatus_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string LeaveStatus_Text(IOrganizationService service)
        {
            return this.LeaveStatus_OptionSetValue.GetOptionSetText(service, this, "new_overallstatus");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string LeaveStatus_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.LeaveStatus_OptionSetValue.Value);
        }

        /// <summary>
        /// Logical Name: new_leavetype
        /// </summary>
        [AttributeLogicalName("new_leavetype")]
        public eLeaveType? LeaveType
        {
            get
            {
                if (LeaveType_OptionSetValue != null) { return (eLeaveType)LeaveType_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.LeaveType_OptionSetValue = new OptionSetValue((int)value); }
                else this.LeaveType_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_leavetype</para>
        /// </summary>
        [AttributeLogicalName("new_leavetype")]
        public OptionSetValue LeaveType_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("new_leavetype");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("new_leavetype", value, "LeaveType_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string LeaveType_Text(IOrganizationService service)
        {
            return this.LeaveType_OptionSetValue.GetOptionSetText(service, this, "new_leavetype");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string LeaveType_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.LeaveType_OptionSetValue.Value);
        }

        /// <summary>
        /// Logical Name: new_managerapproval
        /// </summary>
        [AttributeLogicalName("new_managerapproval")]
        public eApprovalStatus? ManagerApproval
        {
            get
            {
                if (ManagerApproval_OptionSetValue != null) { return (eApprovalStatus)ManagerApproval_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.ManagerApproval_OptionSetValue = new OptionSetValue((int)value); }
                else this.ManagerApproval_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: new_managerapproval</para>
        /// </summary>
        [AttributeLogicalName("new_managerapproval")]
        public OptionSetValue ManagerApproval_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("new_managerapproval");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("new_managerapproval", value, "ManagerApproval_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string ManagerApproval_Text(IOrganizationService service)
        {
            return this.ManagerApproval_OptionSetValue.GetOptionSetText(service, this, "new_managerapproval");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string ManagerApproval_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.ManagerApproval_OptionSetValue.Value);
        }

        /// <summary>
        /// <para>Logical Name: modifiedby</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        public EntityReference ModifiedBy
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfby</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        public EntityReference ModifiedBy_Delegate
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("modifiedonbehalfby");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedon</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        public DateTime? ModifiedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("modifiedon");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedbyname")]
        public string ModifiedByName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedbyyominame")]
        public string ModifiedByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfbyname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfbyname")]
        public string ModifiedOnBehalfByName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedonbehalfbyname");
            }
        }

        /// <summary>
        /// <para>Logical Name: modifiedonbehalfbyyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfbyyominame")]
        public string ModifiedOnBehalfByYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("modifiedonbehalfbyyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_name</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("new_name")]
        public string Name
        {
            get
            {
                return this.GetPropertyValue<string>("new_name");
            }
            set
            {
                this.SetPropertyValue("new_name", value, 100, "Name");
            }
        }






        /// <summary>
        /// <para>Logical Name: new_numberofdays</para>
        /// <para>Minimum Value: 0.5</para>
        /// <para>Maximum Value: 2000</para>
        /// <para>Precision: 1</para>
        /// </summary>
        [AttributeLogicalName("new_numberofdays")]
        public decimal? NumberOfDays
        {
            get
            {
                return this.GetPropertyValue<decimal?>("new_numberofdays");
            }
            set
            {
                this.SetPropertyValue("new_numberofdays", (decimal?)value, (decimal)0.5, (decimal)2000, "NumberOfDays");
            }
        }

        /// <summary>
        /// <para>Logical Name: ownerid</para>
        /// </summary>
        [AttributeLogicalName("ownerid")]
        public EntityReference Owner
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("ownerid");
            }
            set
            {
                this.SetPropertyValue<EntityReference>("ownerid", value, "Owner");
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridname</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("owneridname")]
        public string OwnerIdName
        {
            get
            {
                return this.GetPropertyValue<string>("owneridname");
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridtype</para>
        /// </summary>
        [AttributeLogicalName("owneridtype")]
        public string OwnerIdType
        {
            get
            {
                return this.GetPropertyValue<string>("owneridtype");
            }
            set
            {
                this.SetPropertyValue<string>("owneridtype", value, "OwnerIdType");
            }
        }

        /// <summary>
        /// <para>Logical Name: owneridyominame</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("owneridyominame")]
        public string OwnerIdYomiName
        {
            get
            {
                return this.GetPropertyValue<string>("owneridyominame");
            }
        }

        /// <summary>
        /// <para>Logical Name: owningbusinessunit</para>
        /// </summary>
        [AttributeLogicalName("owningbusinessunit")]
        public EntityReference OwningBusinessUnit
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owningbusinessunit");
            }
        }

        /// <summary>
        /// <para>Logical Name: owningteam</para>
        /// </summary>
        [AttributeLogicalName("owningteam")]
        public EntityReference OwningTeam
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owningteam");
            }
        }

        /// <summary>
        /// <para>Logical Name: owninguser</para>
        /// </summary>
        [AttributeLogicalName("owninguser")]
        public EntityReference OwningUser
        {
            get
            {
                return this.GetPropertyValue<EntityReference>("owninguser");
            }
        }

        /// <summary>
        /// <para>Logical Name: processid</para>
        /// </summary>
        [AttributeLogicalName("processid")]
        public Guid ProcessId
        {
            get
            {
                return this.GetPropertyValue<Guid>("processid");
            }
            set
            {
                this.SetPropertyValue<Guid>("processid", value, "ProcessId");
            }
        }

        /// <summary>
        /// <para>Logical Name: overriddencreatedon</para>
        /// </summary>
        [AttributeLogicalName("overriddencreatedon")]
        public DateTime? RecordCreatedOn
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("overriddencreatedon");
            }
            set
            {
                this.SetPropertyValue<DateTime?>("overriddencreatedon", value, "RecordCreatedOn");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_requestno</para>
        /// <para>Max Length: 100 characters</para>
        /// </summary>
        [AttributeLogicalName("new_requestno")]
        public string RequestNo
        {
            get
            {
                return this.GetPropertyValue<string>("new_requestno");
            }
            set
            {
                this.SetPropertyValue("new_requestno", value, 100, "RequestNo");
            }
        }

        /// <summary>
        /// <para>Logical Name: new_startdate</para>
        /// </summary>
        [AttributeLogicalName("new_startdate")]
        public DateTime? StartDate
        {
            get
            {
                return this.GetPropertyValue<DateTime?>("new_startdate");
            }
            set
            {
                this.SetPropertyValue<DateTime?>("new_startdate", value, "StartDate");
            }
        }


        /// <summary>
        /// Logical Name: statecode
        /// </summary>
        [AttributeLogicalName("statecode")]
        public eLeaveRequests_Status? Status
        {
            get
            {
                if (Status_OptionSetValue != null) { return (eLeaveRequests_Status)Status_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.Status_OptionSetValue = new OptionSetValue((int)value); }
                else this.Status_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: statecode</para>
        /// </summary>
        [AttributeLogicalName("statecode")]
        public OptionSetValue Status_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("statecode");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("statecode", value, "Status_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string Status_Text(IOrganizationService service)
        {
            return this.Status_OptionSetValue.GetOptionSetText(service, this, "statecode");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string Status_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.Status_OptionSetValue.Value);
        }

        /// <summary>
        /// Logical Name: statuscode
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public eLeaveRequests_StatusReason? StatusReason
        {
            get
            {
                if (StatusReason_OptionSetValue != null) { return (eLeaveRequests_StatusReason)StatusReason_OptionSetValue.Value; }
                return null;
            }
            set
            {
                if (value != null) { this.StatusReason_OptionSetValue = new OptionSetValue((int)value); }
                else this.StatusReason_OptionSetValue = null;
            }
        }
        /// <summary>
        /// <para>Logical Name: statuscode</para>
        /// </summary>
        [AttributeLogicalName("statuscode")]
        public OptionSetValue StatusReason_OptionSetValue
        {
            get
            {
                return this.GetPropertyValue<OptionSetValue>("statuscode");
            }
            set
            {
                this.SetPropertyValue<OptionSetValue>("statuscode", value, "StatusReason_OptionSetValue");
            }
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="Service">CRM Organization Service</param>
        /// <returns></returns>
        public string StatusReason_Text(IOrganizationService service)
        {
            return this.StatusReason_OptionSetValue.GetOptionSetText(service, this, "statuscode");
        }
        /// <summary>
        /// Retrieves the current value's text in the user's language.
        /// </summary>
        /// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
        /// <returns></returns>
        public string StatusReason_Text(EnumAttributeMetadata attributeMetadata)
        {
            return attributeMetadata.GetOptionSetText(this.StatusReason_OptionSetValue.Value);
        }


        /// <summary>
        /// <para>Logical Name: timezoneruleversionnumber</para>
        /// <para>Minimum Value: -1</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("timezoneruleversionnumber")]
        public int? TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("timezoneruleversionnumber");
            }
            set
            {
                this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, "TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// <para>Logical Name: utcconversiontimezonecode</para>
        /// <para>Minimum Value: -1</para>
        /// <para>Maximum Value: 2147483647</para>
        /// </summary>
        [AttributeLogicalName("utcconversiontimezonecode")]
        public int? UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetPropertyValue<int?>("utcconversiontimezonecode");
            }
            set
            {
                this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, "UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
        /// <para>Logical Name: versionnumber</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        public int? VersionNumber
        {
            get
            {
                return this.GetPropertyValue<int?>("versionnumber");
            }
        }


        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_leaverequests_AsyncOperations</para>
        /// </summary>
        public List<Entity> GetSystemJobs_Regarding(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "asyncoperation", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_leaverequests_AsyncOperations</para>
        /// </summary>
        public List<Entity> GetSystemJobs_Regarding(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "asyncoperation", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Name)</b></para>
        /// <para>Schema Name: new_leaverequests_BulkDeleteFailures</para>
        /// </summary>
        public List<Entity> GetBulkDeleteFailures_Name(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "bulkdeletefailure", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Name)</b></para>
        /// <para>Schema Name: new_leaverequests_BulkDeleteFailures</para>
        /// </summary>
        public List<Entity> GetBulkDeleteFailures_Name(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "bulkdeletefailure", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Base Record ID)</b></para>
        /// <para>Schema Name: new_leaverequests_DuplicateBaseRecord</para>
        /// </summary>
        public List<Entity> GetDuplicateRecords_BaseRecordID(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "duplicaterecord", "baserecordid", columns); }

        /// <summary>
        /// <para><b>Entity (Base Record ID)</b></para>
        /// <para>Schema Name: new_leaverequests_DuplicateBaseRecord</para>
        /// </summary>
        public List<Entity> GetDuplicateRecords_BaseRecordID(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "duplicaterecord", "baserecordid", columns); }

        /// <summary>
        /// <para><b>Entity (Duplicate Record ID)</b></para>
        /// <para>Schema Name: new_leaverequests_DuplicateMatchingRecord</para>
        /// </summary>
        public List<Entity> GetDuplicateRecords_DuplicateRecordID(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "duplicaterecord", "duplicaterecordid", columns); }

        /// <summary>
        /// <para><b>Entity (Duplicate Record ID)</b></para>
        /// <para>Schema Name: new_leaverequests_DuplicateMatchingRecord</para>
        /// </summary>
        public List<Entity> GetDuplicateRecords_DuplicateRecordID(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "duplicaterecord", "duplicaterecordid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding Object Id)</b></para>
        /// <para>Schema Name: new_leaverequests_MailboxTrackingFolders</para>
        /// </summary>
        public List<Entity> GetMailboxAutoTrackingFolders_RegardingObjectId(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "mailboxtrackingfolder", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding Object Id)</b></para>
        /// <para>Schema Name: new_leaverequests_MailboxTrackingFolders</para>
        /// </summary>
        public List<Entity> GetMailboxAutoTrackingFolders_RegardingObjectId(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "mailboxtrackingfolder", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (New_Leaverequests)</b></para>
        /// <para>Schema Name: bpf_new_leaverequests_new_leaveapprovalprocess</para>
        /// </summary>
        public List<Entity> GetLeaveApprovalProcess_New_Leaverequests(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "new_leaveapprovalprocess", "bpf_new_leaverequestsid", columns); }

        /// <summary>
        /// <para><b>Entity (New_Leaverequests)</b></para>
        /// <para>Schema Name: bpf_new_leaverequests_new_leaveapprovalprocess</para>
        /// </summary>
        public List<Entity> GetLeaveApprovalProcess_New_Leaverequests(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "new_leaveapprovalprocess", "bpf_new_leaverequestsid", columns); }

        /// <summary>
        /// <para><b>Entity (Entity instance)</b></para>
        /// <para>Schema Name: new_leaverequests_PrincipalObjectAttributeAccesses</para>
        /// </summary>
        public List<Entity> GetFieldSharing_EntityInstance(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "principalobjectattributeaccess", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Entity instance)</b></para>
        /// <para>Schema Name: new_leaverequests_PrincipalObjectAttributeAccesses</para>
        /// </summary>
        public List<Entity> GetFieldSharing_EntityInstance(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "principalobjectattributeaccess", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_leaverequests_ProcessSession</para>
        /// </summary>
        public List<Entity> GetProcessSessions_Regarding(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "processsession", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Regarding)</b></para>
        /// <para>Schema Name: new_leaverequests_ProcessSession</para>
        /// </summary>
        public List<Entity> GetProcessSessions_Regarding(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "processsession", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Record)</b></para>
        /// <para>Schema Name: new_leaverequests_SyncErrors</para>
        /// </summary>
        public List<Entity> GetSyncErrors_Record(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "syncerror", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Record)</b></para>
        /// <para>Schema Name: new_leaverequests_SyncErrors</para>
        /// </summary>
        public List<Entity> GetSyncErrors_Record(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "syncerror", "regardingobjectid", columns); }

        /// <summary>
        /// <para><b>Entity (Object Id)</b></para>
        /// <para>Schema Name: new_leaverequests_UserEntityInstanceDatas</para>
        /// </summary>
        public List<Entity> GetUserEntityInstanceData_ObjectId(IOrganizationService service, params string[] columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "userentityinstancedata", "objectid", columns); }

        /// <summary>
        /// <para><b>Entity (Object Id)</b></para>
        /// <para>Schema Name: new_leaverequests_UserEntityInstanceDatas</para>
        /// </summary>
        public List<Entity> GetUserEntityInstanceData_ObjectId(IOrganizationService service, ColumnSet columns) { return BaseProxyClass.GetRelatedOneToManyEntities(service, this.Id, "userentityinstancedata", "objectid", columns); }


        
        
        
        public static class Properties
        {
            /// <summary>
            /// <para>(Deprecated) Stage Id</para>
            /// <para>Logical Name = stageid</para>
            /// </summary>
            public const string _Deprecated_StageId = "stageid";

            /// <summary>
            /// <para>(Deprecated) Traversed Path</para>
            /// <para>Logical Name = traversedpath</para>
            /// </summary>
            public const string _Deprecated_TraversedPath = "traversedpath";

            /// <summary>
            /// <para>comments</para>
            /// <para>Logical Name = new_comments</para>
            /// </summary>
            public const string Comments = "new_comments";

            /// <summary>
            /// <para>Created By</para>
            /// <para>Logical Name = createdby</para>
            /// </summary>
            public const string CreatedBy = "createdby";

            /// <summary>
            /// <para>Created By (Delegate)</para>
            /// <para>Logical Name = createdonbehalfby</para>
            /// </summary>
            public const string CreatedBy_Delegate = "createdonbehalfby";

            /// <summary>
            /// <para>Created On</para>
            /// <para>Logical Name = createdon</para>
            /// </summary>
            public const string CreatedOn = "createdon";

            /// <summary>
            /// <para>Logical Name = createdbyname</para>
            /// </summary>
            public const string CreatedByName = "createdbyname";

            /// <summary>
            /// <para>Logical Name = createdbyyominame</para>
            /// </summary>
            public const string CreatedByYomiName = "createdbyyominame";

            /// <summary>
            /// <para>Logical Name = createdonbehalfbyname</para>
            /// </summary>
            public const string CreatedOnBehalfByName = "createdonbehalfbyname";

            /// <summary>
            /// <para>Logical Name = createdonbehalfbyyominame</para>
            /// </summary>
            public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";

            /// <summary>
            /// <para>End Date</para>
            /// <para>Logical Name = new_enddate</para>
            /// </summary>
            public const string EndDate = "new_enddate";

            /// <summary>
            /// <para>Half Day</para>
            /// <para>Logical Name = new_halfday</para>
            /// </summary>
            public const string HalfDay = "new_halfday";

            /// <summary>
            /// <para>HR Approval</para>
            /// <para>Logical Name = new_hrapproval</para>
            /// </summary>
            public const string HRApproval = "new_hrapproval";

            /// <summary>
            /// <para>Import Sequence Number</para>
            /// <para>Logical Name = importsequencenumber</para>
            /// </summary>
            public const string ImportSequenceNumber = "importsequencenumber";

            /// <summary>
            /// <para>Leave Requests</para>
            /// <para>Logical Name = new_leaverequestsid</para>
            /// </summary>
            public const string LeaveRequestsId = "new_leaverequestsid";

            /// <summary>
            /// <para>Leave Status</para>
            /// <para>Logical Name = new_overallstatus</para>
            /// </summary>
            public const string LeaveStatus = "new_overallstatus";

            /// <summary>
            /// <para>Leave Type</para>
            /// <para>Logical Name = new_leavetype</para>
            /// </summary>
            public const string LeaveType = "new_leavetype";

            /// <summary>
            /// <para>Manager Approval</para>
            /// <para>Logical Name = new_managerapproval</para>
            /// </summary>
            public const string ManagerApproval = "new_managerapproval";

            /// <summary>
            /// <para>Modified By</para>
            /// <para>Logical Name = modifiedby</para>
            /// </summary>
            public const string ModifiedBy = "modifiedby";

            /// <summary>
            /// <para>Modified By (Delegate)</para>
            /// <para>Logical Name = modifiedonbehalfby</para>
            /// </summary>
            public const string ModifiedBy_Delegate = "modifiedonbehalfby";

            /// <summary>
            /// <para>Modified On</para>
            /// <para>Logical Name = modifiedon</para>
            /// </summary>
            public const string ModifiedOn = "modifiedon";

            /// <summary>
            /// <para>Logical Name = modifiedbyname</para>
            /// </summary>
            public const string ModifiedByName = "modifiedbyname";

            /// <summary>
            /// <para>Logical Name = modifiedbyyominame</para>
            /// </summary>
            public const string ModifiedByYomiName = "modifiedbyyominame";

            /// <summary>
            /// <para>Logical Name = modifiedonbehalfbyname</para>
            /// </summary>
            public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";

            /// <summary>
            /// <para>Logical Name = modifiedonbehalfbyyominame</para>
            /// </summary>
            public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";

            /// <summary>
            /// <para>Name</para>
            /// <para>Logical Name = new_name</para>
            /// </summary>
            public const string Name = "new_name";

            /// <summary>
            /// <para>Logical Name = new_halfdayname</para>
            /// </summary>
            public const string New_halfdayName = "new_halfdayname";

            /// <summary>
            /// <para>Logical Name = new_hrapprovalname</para>
            /// </summary>
            public const string New_hrapprovalName = "new_hrapprovalname";

            /// <summary>
            /// <para>Logical Name = new_leavetypename</para>
            /// </summary>
            public const string New_leavetypeName = "new_leavetypename";

            /// <summary>
            /// <para>Logical Name = new_managerapprovalname</para>
            /// </summary>
            public const string New_managerapprovalName = "new_managerapprovalname";

            /// <summary>
            /// <para>Logical Name = new_overallstatusname</para>
            /// </summary>
            public const string New_overallstatusName = "new_overallstatusname";

            /// <summary>
            /// <para>Number of Days</para>
            /// <para>Logical Name = new_numberofdays</para>
            /// </summary>
            public const string NumberOfDays = "new_numberofdays";

            /// <summary>
            /// <para>Owner</para>
            /// <para>Logical Name = ownerid</para>
            /// </summary>
            public const string Owner = "ownerid";

            /// <summary>
            /// <para>Logical Name = owneridname</para>
            /// </summary>
            public const string OwnerIdName = "owneridname";

            /// <summary>
            /// <para>Logical Name = owneridtype</para>
            /// </summary>
            public const string OwnerIdType = "owneridtype";

            /// <summary>
            /// <para>Logical Name = owneridyominame</para>
            /// </summary>
            public const string OwnerIdYomiName = "owneridyominame";

            /// <summary>
            /// <para>Owning Business Unit</para>
            /// <para>Logical Name = owningbusinessunit</para>
            /// </summary>
            public const string OwningBusinessUnit = "owningbusinessunit";

            /// <summary>
            /// <para>Owning Team</para>
            /// <para>Logical Name = owningteam</para>
            /// </summary>
            public const string OwningTeam = "owningteam";

            /// <summary>
            /// <para>Owning User</para>
            /// <para>Logical Name = owninguser</para>
            /// </summary>
            public const string OwningUser = "owninguser";

            /// <summary>
            /// <para>Process Id</para>
            /// <para>Logical Name = processid</para>
            /// </summary>
            public const string ProcessId = "processid";

            /// <summary>
            /// <para>Record Created On</para>
            /// <para>Logical Name = overriddencreatedon</para>
            /// </summary>
            public const string RecordCreatedOn = "overriddencreatedon";

            /// <summary>
            /// <para>Request No #</para>
            /// <para>Logical Name = new_requestno</para>
            /// </summary>
            public const string RequestNo = "new_requestno";

            /// <summary>
            /// <para>Start Date</para>
            /// <para>Logical Name = new_startdate</para>
            /// </summary>
            public const string StartDate = "new_startdate";

            /// <summary>
            /// <para>Logical Name = statecodename</para>
            /// </summary>
            public const string StatecodeName = "statecodename";

            /// <summary>
            /// <para>Status</para>
            /// <para>Logical Name = statecode</para>
            /// </summary>
            public const string Status = "statecode";

            /// <summary>
            /// <para>Status Reason</para>
            /// <para>Logical Name = statuscode</para>
            /// </summary>
            public const string StatusReason = "statuscode";

            /// <summary>
            /// <para>Logical Name = statuscodename</para>
            /// </summary>
            public const string StatuscodeName = "statuscodename";

            /// <summary>
            /// <para>Time Zone Rule Version Number</para>
            /// <para>Logical Name = timezoneruleversionnumber</para>
            /// </summary>
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";

            /// <summary>
            /// <para>UTC Conversion Time Zone Code</para>
            /// <para>Logical Name = utcconversiontimezonecode</para>
            /// </summary>
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";

            /// <summary>
            /// <para>Version Number</para>
            /// <para>Logical Name = versionnumber</para>
            /// </summary>
            public const string VersionNumber = "versionnumber";

        }

    }
}
